config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resources :orders
  resources :products
  resources :sellers

  resource  :cart#, only: [:show]
  resources :order_items#, only: [:create, :update, :destroy]

  root 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :seller
  has_many   :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_order
  if !session[:order_id].nil?
    Order.find(session[:order_id])
  else
    Order.new
  end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:client_name, :Seller_id, :Product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sellers = Seller.all
    respond_with(@sellers)
  end

  def show
    respond_with(@seller)
  end

  def new
    @seller = Seller.new
    respond_with(@seller)
  end

  def edit
  end

  def create
    @seller = Seller.new(seller_params)
    @seller.save
    respond_with(@seller)
  end

  def update
    @seller.update(seller_params)
    respond_with(@seller)
  end

  def destroy
    @seller.destroy
    respond_with(@seller)
  end

  private
    def set_seller
      @seller = Seller.find(params[:id])
    end

    def seller_params
      params.require(:seller).permit(:name, :registration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ffitshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :seller_id %><br>
    <%= f.text_field :seller_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Seller</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.client_name %></td>
        <td><%= order.Seller %></td>
        <td><%= order.Product %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @order.client_name %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @order.Seller %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.Product %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, price: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, price: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :registration %><br>
    <%= f.text_field :registration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= seller.registration %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New Seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @seller.registration %>
</p>

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>